const dataanswers = [

    {
        title: 'April 8',
        data: ['Q: Among these phrases, “a rain of flowers,” “mystical mirage,” and “vivid carp streamers,” which one symbolizes summer?', 'A: Vivid Carp Streamers'],
    },
    {
        title: 'April 18',
        data: ['Q: The places where people dumped their waste in the Jomon period, what are they called nowadays?', 'A: Middens'],
    },
    {
        title: 'April 27',
        data: ['Q: Do you know which ones not an algebraic spiral or whatever?', 'A: A'],
    },
    {
        title: 'May 6',
        data: ['Q: What do you call the device that helps generate electric power for the train?', 'A: A pantograph'],
    },
    {
        title: 'May 13',
        data: ['Q: Do you know Leon Foucault? He’s a French physicist who performed experiments regarding the rotation of the Earth. Which tool did he use in his experiments?', 'A: The pendulum'],
    },
    {
        title: 'May 15',
        data: ['Q: Q: What’s the other name for “May sickness” — the more casual one?', 'A: May Blues'],
    },
    {
        title: 'May 19 (Exam)',
        data: ['Q: What is the other common expression used to describe “May sickness?', 'A: May Blues'],
    },
    {
        title: 'May 20 (Exam)',
        data: ['Q: Which of the following did Leon Foucault use in his experiment on the rotation of the Earth?', 'A: A pendulum'],
    },
    {
        title: 'May 21 (Exam)',
        data: ['Q: Which of the following is generated by a pantograph?', 'A: Electricity'],
    },
    {
        title: 'May 22 (Exam)',
        data: ['Q: During which historical period were middens most commonly used?', 'A: Jomon'],
    },
    {
        title: 'June 15',
        data: ['Q: Which phrase means, “Able to see things for what they really are?”', 'A: Keen Eye'],
    },
    {
        title: 'June 17',
        data: ['Q: What early religious practice was the origin of magic?', 'A: Shamanism'],
    },
    {
        title: 'June 22',
        data: ['Q: What else do people call this curve?', 'A: Witch of Agnesi'],
    },
];

export default dataanswers;